export const CHOOSE_CONTENT_TYPE = 'CHOOSE_CONTENT_TYPE';
export const REQUEST_CONTENT = 'REQUEST_CONTENT';
export const REQUESTED_CONTENT = 'REQUESTED_CONTENT';
export const RECEIVE_CONTENT = 'RECEIVE_CONTENT';
export const UPDATE_CONTENT = 'UPDATE_CONTENT';
export const ADD_ITEM = 'ADD_ITEM';
export const RESET_REQUET_STATUS = 'RESET_REQUET_STATUS';
